services:
  db:
    image: postgres:latest
    container_name: shoplog-db
    restart: always
    healthcheck:
      test:
        ['CMD', 'pg_isready', '-q', '-d', 'postgres', '-U', '${DATABASE_USER}']
      timeout: 5s
      interval: 10s
      retries: 5
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - '${DATABASE_PORT}:${DATABASE_PORT}'
    volumes:
      - ./.docker/db:/var/lib/postgresql/data
  # redis:
  #   image: redis:latest
  #   restart: always
  #   healthcheck:
  #     test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
  #   ports:
  #     - '${REDIS_PORT}:${REDIS_PORT}'
  #   environment:
  #     REDIS_PASSWORD: ${REDIS_PASSWORD}
  #     ALLOW_EMPTY_PASSWORD: no
